import { Image } from "expo-image";
import type { ImageStyle, StyleProp } from "react-native";

const assets = {
  mascotCheerful: require("@/assets/brand/mascots/cheerful.png"),
  mascotSupportive: require("@/assets/brand/mascots/supportive.png"),
  mascotCurious: require("@/assets/brand/mascots/curious.png"),
  mascotCelebrating: require("@/assets/brand/mascots/celebrating.png"),
  mascotReading: require("@/assets/brand/mascots/reading.png"),
  mascotActive: require("@/assets/brand/mascots/active.png"),
  mascotFocused: require("@/assets/brand/mascots/focused.png"),
  mascotCheering: require("@/assets/brand/mascots/cheering.png"),
  mascotPrediction: require("@/assets/brand/mascots/prediction.png"),
  iconStudy: require("@/assets/brand/icons/study.png"),
  iconFitness: require("@/assets/brand/icons/fitness.png"),
  iconLifestyle: require("@/assets/brand/icons/lifestyle.png"),
  iconPoints: require("@/assets/brand/icons/points.png"),
  iconStreak: require("@/assets/brand/icons/streak.png"),
  iconAiInsight: require("@/assets/brand/icons/aiInsight.png"),
  iconTrophy: require("@/assets/brand/icons/trophy.png"),
  iconLeaderboard: require("@/assets/brand/icons/leaderboard.png"),
  iconShop: require("@/assets/brand/icons/shop.png"),
  iconPrediction: require("@/assets/brand/icons/prediction.png"),
  iconConfidence: require("@/assets/brand/icons/confidence.png"),
  iconSuccess: require("@/assets/brand/icons/success.png"),
  iconFailed: require("@/assets/brand/icons/failed.png"),
  iconChallenge: require("@/assets/brand/icons/challenge.png"),
  badgeFirstChallenge: require("@/assets/brand/badges/firstChallenge.png"),
  badgeThreeDayStreak: require("@/assets/brand/badges/threeDayStreak.png"),
  badgeSevenDayStreak: require("@/assets/brand/badges/sevenDayStreak.png"),
  badgeKnowledgeBuilder: require("@/assets/brand/badges/knowledgeBuilder.png"),
  badgeFitnessHero: require("@/assets/brand/badges/fitnessHero.png"),
  badgeEarlyBird: require("@/assets/brand/badges/earlyBird.png"),
  badgeAiSlayer: require("@/assets/brand/badges/aiSlayer.png"),
  badgeConsistency: require("@/assets/brand/badges/consistency.png"),
  frameSunny: require("@/assets/brand/frames/sunny.png"),
  framePurpleAura: require("@/assets/brand/frames/purpleAura.png"),
  frameGalaxy: require("@/assets/brand/frames/galaxy.png"),
  frameFire: require("@/assets/brand/frames/fire.png"),
  rewardFocusBeats: require("@/assets/brand/rewards/focusBeats.png"),
  rewardBookLover: require("@/assets/brand/rewards/bookLover.png"),
  rewardPlantBuddy: require("@/assets/brand/rewards/plantBuddy.png"),
  rewardChillCap: require("@/assets/brand/rewards/chillCap.png"),
  decoSparkleBlue: require("@/assets/brand/decor/sparkleBlue.png"),
  stickerKeepGoing: require("@/assets/brand/stickers/keepGoing.png"),
  stickerSmallSteps: require("@/assets/brand/stickers/smallSteps.png"),
  stickerYouGotThis: require("@/assets/brand/stickers/youGotThis.png"),
  stickerBrighterDays: require("@/assets/brand/stickers/brighterDays.png"),
  stickerFocused: require("@/assets/brand/stickers/focused.png"),
  stickerBigDreamer: require("@/assets/brand/stickers/bigDreamer.png"),
  stickerYouCalledIt: require("@/assets/brand/stickers/youCalledIt.png"),
  statePredicting: require("@/assets/brand/states/predicting.png"),
  statePointsEarned: require("@/assets/brand/states/pointsEarned.png"),
  stateChallengeSuccess: require("@/assets/brand/states/challengeSuccess.png"),
  stateChallengeFailed: require("@/assets/brand/states/challengeFailed.png"),
  stateNoChallenges: require("@/assets/brand/states/noChallenges.png"),
  stateNoFriends: require("@/assets/brand/states/noFriends.png"),
  mascotCelebrate: require("@/assets/brand/mascots/mascot_celebrate.png"),
  mascotTrophy: require("@/assets/brand/mascots/mascot_trophy.png"),
  mascotStreak: require("@/assets/brand/mascots/mascot_streak.png"),
  mascotStudying: require("@/assets/brand/mascots/mascot_studying.png"),
  mascotBedtime: require("@/assets/brand/mascots/mascot_bedtime.png"),
  mascotMorning: require("@/assets/brand/mascots/mascot_morning.png"),
  mascotHeart: require("@/assets/brand/mascots/mascot_heart.png"),
  mascotPoints: require("@/assets/brand/mascots/mascot_points.png"),
  mascotQuestion: require("@/assets/brand/mascots/mascot_question.png"),
  mascotIdea: require("@/assets/brand/mascots/mascot_idea.png"),
  mascotStar: require("@/assets/brand/mascots/mascot_star.png"),
  stateNewBadgeUnlocked: require("@/assets/brand/states/state_new_badge_unlocked.png"),
  stateAiAnalyzing: require("@/assets/brand/states/state_ai_analyzing.png"),
  stateAiPredictionReady: require("@/assets/brand/states/state_ai_prediction_ready.png"),
  stateNoRewards: require("@/assets/brand/states/state_no_rewards.png"),
  stateStreakContinues: require("@/assets/brand/states/state_streak_continues.png"),
  stateNetworkError: require("@/assets/brand/states/state_network_error.png"),
  statePurchaseComplete: require("@/assets/brand/states/state_purchase_complete.png"),
  stateLevelUp: require("@/assets/brand/states/state_level_up.png"),
  stateNoPredictions: require("@/assets/brand/states/state_no_predictions.png"),
  frameMidnight: require("@/assets/brand/frames/frame_midnight.png"),
  frameChampion: require("@/assets/brand/frames/frame_champion.png"),
  frameRainbow: require("@/assets/brand/frames/frame_rainbow.png"),
  frameAi: require("@/assets/brand/frames/frame_ai.png"),
  frameLove: require("@/assets/brand/frames/frame_love.png"),
  frameMintNature: require("@/assets/brand/frames/frame_mint_nature.png"),
  frameStar: require("@/assets/brand/frames/frame_star.png"),
  frameMintFlame: require("@/assets/brand/frames/frame_mint_flame.png"),
  frameBlueFlame: require("@/assets/brand/frames/frame_blue_flame.png"),
  frameGoldenSun: require("@/assets/brand/frames/frame_golden_sun.png"),
  iconRewardShop: require("@/assets/brand/icons/icon_reward_shop.png"),
  iconPointsClassic: require("@/assets/brand/icons/icon_points.png"),
  iconFitnessClassic: require("@/assets/brand/icons/icon_fitness.png"),
  categoryWakeUp: require("@/assets/brand/icons/category_wake_up.png"),
  categoryMindfulness: require("@/assets/brand/icons/category_mindfulness.png"),
  iconAiInsightV2: require("@/assets/brand/icons/icon_ai_insight_v2.png"),
  iconRewards: require("@/assets/brand/icons/icon_rewards.png"),
  iconStudyV2: require("@/assets/brand/icons/icon_study_v2.png"),
  iconLifestyleV2: require("@/assets/brand/icons/icon_lifestyle_v2.png"),
  iconPointsV2: require("@/assets/brand/icons/icon_points_v2.png"),
  statusLocked: require("@/assets/brand/icons/status_locked.png"),
  iconTrophyClassic: require("@/assets/brand/icons/icon_trophy.png"),
  statusDown: require("@/assets/brand/icons/status_down.png"),
  iconRewardShopV2: require("@/assets/brand/icons/icon_reward_shop_v2.png"),
  iconStreakClassic: require("@/assets/brand/icons/icon_streak.png"),
  categoryHealth: require("@/assets/brand/icons/category_health.png"),
  categorySocial: require("@/assets/brand/icons/category_social.png"),
  iconFailedClassic: require("@/assets/brand/icons/icon_failed.png"),
  iconLifestyleClassic: require("@/assets/brand/icons/icon_lifestyle.png"),
  iconTrophyV2: require("@/assets/brand/icons/icon_trophy_v2.png"),
  iconFitnessV2: require("@/assets/brand/icons/icon_fitness_v2.png"),
  iconStreakV2: require("@/assets/brand/icons/icon_streak_v2.png"),
  statusUp: require("@/assets/brand/icons/status_up.png"),
  iconLevelUp: require("@/assets/brand/icons/icon_level_up.png"),
  categoryProductivity: require("@/assets/brand/icons/category_productivity.png"),
  iconStudyClassic: require("@/assets/brand/icons/icon_study.png"),
  categorySleep: require("@/assets/brand/icons/category_sleep.png"),
  iconAiInsightClassic: require("@/assets/brand/icons/icon_ai_insight.png"),
  iconSuccessClassic: require("@/assets/brand/icons/icon_success.png"),
  badgeMiniFirstChallenge: require("@/assets/brand/badges/badge_mini_first_challenge.png"),
  badge7DayStreak: require("@/assets/brand/badges/badge_7_day_streak.png"),
  badgeChallengeChampion: require("@/assets/brand/badges/badge_challenge_champion.png"),
  badgeMiniFitnessHero: require("@/assets/brand/badges/badge_mini_fitness_hero.png"),
  badgePredictionMaster: require("@/assets/brand/badges/badge_prediction_master.png"),
  badgeMiniSocialButterfly: require("@/assets/brand/badges/badge_mini_social_butterfly.png"),
  badgeNightOwl: require("@/assets/brand/badges/badge_night_owl.png"),
  badgeFocusMode: require("@/assets/brand/badges/badge_focus_mode.png"),
  badgeMiniConsistentYou: require("@/assets/brand/badges/badge_mini_consistent_you.png"),
  badgeStreakStarter: require("@/assets/brand/badges/badge_streak_starter.png"),
  badge30DayStreak: require("@/assets/brand/badges/badge_30_day_streak.png"),
  badgeFirstChallengeV2: require("@/assets/brand/badges/badge_first_challenge_v2.png"),
  badgeHabitHero: require("@/assets/brand/badges/badge_habit_hero.png"),
  badgeAiExplorer: require("@/assets/brand/badges/badge_ai_explorer.png"),
  badgePositiveHabits: require("@/assets/brand/badges/badge_positive_habits.png"),
  badgeBigAchiever: require("@/assets/brand/badges/badge_big_achiever.png"),
  badge7DayStreakV2: require("@/assets/brand/badges/badge_7_day_streak_v2.png"),
  badgeComeback: require("@/assets/brand/badges/badge_comeback.png"),
  badge14DayStreak: require("@/assets/brand/badges/badge_14_day_streak.png"),
  badgeFitnessHeroClassic: require("@/assets/brand/badges/badge_fitness_hero.png"),
  badgeMiniBigAchiever: require("@/assets/brand/badges/badge_mini_big_achiever.png"),
  badgeKnowledgeBuilderV2: require("@/assets/brand/badges/badge_knowledge_builder_v2.png"),
  badgeRewardHunter: require("@/assets/brand/badges/badge_reward_hunter.png"),
  badgePerfectWeek: require("@/assets/brand/badges/badge_perfect_week.png"),
  badgeFirstChallengeClassic: require("@/assets/brand/badges/badge_first_challenge.png"),
  badgeMiniKnowledge: require("@/assets/brand/badges/badge_mini_knowledge.png"),
  badgeMiniPositiveMindset: require("@/assets/brand/badges/badge_mini_positive_mindset.png"),
  badgeKnowledgeBuilderClassic: require("@/assets/brand/badges/badge_knowledge_builder.png"),
  badgeSocialButterfly: require("@/assets/brand/badges/badge_social_butterfly.png"),
  badgeMini7DayStreak: require("@/assets/brand/badges/badge_mini_7_day_streak.png"),
  badgePointsCollector: require("@/assets/brand/badges/badge_points_collector.png"),
  badgeGoalGetter: require("@/assets/brand/badges/badge_goal_getter.png"),
  badgeFitnessHeroV2: require("@/assets/brand/badges/badge_fitness_hero_v2.png"),
  decoPlant: require("@/assets/brand/decor/deco_plant.png"),
  decoHeart: require("@/assets/brand/decor/deco_heart.png"),
  decoArrowCurved: require("@/assets/brand/decor/deco_arrow_curved.png"),
  decoSunFace: require("@/assets/brand/decor/deco_sun_face.png"),
  decoArrowBlue: require("@/assets/brand/decor/arrowBlue.png"),
  decoSquiggle: require("@/assets/brand/decor/deco_squiggle.png"),
  decoStar: require("@/assets/brand/decor/deco_star.png"),
  decoLinesBlue: require("@/assets/brand/decor/deco_lines_blue.png"),
  decoPlantBuddy: require("@/assets/brand/decor/deco_plant_buddy.png"),
  decoBurstLines: require("@/assets/brand/decor/deco_burst_lines.png"),
  decoSun: require("@/assets/brand/decor/deco_sun.png"),
  decoStudyStar: require("@/assets/brand/decor/deco_study_star.png"),
  decoHeartV2: require("@/assets/brand/decor/deco_heart_v2.png"),
  decoRainbowStar: require("@/assets/brand/decor/deco_rainbow_star.png"),
  decoRobot: require("@/assets/brand/decor/deco_robot.png"),
  decoStarV2: require("@/assets/brand/decor/star.png"),
  decoCrown: require("@/assets/brand/decor/deco_crown.png"),
  stickerLifePredictionsMadeFun: require("@/assets/brand/stickers/sticker_life_predictions_made_fun.png"),
  stickerYourFutureSelfSaysThanks: require("@/assets/brand/stickers/sticker_your_future_self_says_thanks.png"),
  stickerTitleProgressNotPerfect: require("@/assets/brand/stickers/title_progress_not_perfect.png"),
  stickerEveryPrediction: require("@/assets/brand/stickers/sticker_every_prediction.png"),
  stickerMakeItAHabit: require("@/assets/brand/stickers/sticker_make_it_a_habit.png"),
  stickerYouGotThisMascot: require("@/assets/brand/stickers/sticker_you_got_this_mascot.png"),
  stickerTitleBigDreamer: require("@/assets/brand/stickers/title_big_dreamer.png"),
  stickerPlayfulEditorial: require("@/assets/brand/stickers/sticker_playful_editorial.png"),
  stickerYouGotThisClassic: require("@/assets/brand/stickers/sticker_you_got_this.png"),
  stickerSmallStepsV2: require("@/assets/brand/stickers/sticker_small_steps_v2.png"),
  stickerNicePrediction: require("@/assets/brand/stickers/sticker_nice_prediction.png"),
  stickerTitleFocusedV2: require("@/assets/brand/stickers/title_focused_v2.png"),
  stickerTitleBigDreamerV2: require("@/assets/brand/stickers/title_big_dreamer_v2.png"),
  stickerLevelUp: require("@/assets/brand/stickers/sticker_level_up.png"),
  stickerBuildTheHabit: require("@/assets/brand/stickers/sticker_build_the_habit.png"),
  stickerNewStreak: require("@/assets/brand/stickers/sticker_new_streak.png"),
  sticker21DayStreak: require("@/assets/brand/stickers/sticker_21_day_streak.png"),
  stickerTitleFocused: require("@/assets/brand/stickers/title_focused.png"),
  stickerTitleKindHuman: require("@/assets/brand/stickers/title_kind_human.png"),
  stickerBetterEveryDay: require("@/assets/brand/stickers/sticker_better_every_day.png"),
  stickerBelieveYourData: require("@/assets/brand/stickers/sticker_believe_your_data.png"),
  stickerPredictPlanPlayGrow: require("@/assets/brand/stickers/sticker_predict_plan_play_grow.png"),
  stickerLetsGo: require("@/assets/brand/stickers/sticker_lets_go.png"),
  stickerSameYouBrighterFuture: require("@/assets/brand/stickers/sticker_same_you_brighter_future.png"),
  stickerBrighterDaysOutline: require("@/assets/brand/stickers/sticker_brighter_days_outline.png"),
  stickerGreatJob: require("@/assets/brand/stickers/sticker_great_job.png"),
  sticker87ChanceHappier: require("@/assets/brand/stickers/sticker_87_chance_happier.png"),
  stickerSmallStepsBigResults: require("@/assets/brand/stickers/sticker_small_steps_big_results.png"),
  stickerKeepTheMomentum: require("@/assets/brand/stickers/sticker_keep_the_momentum.png"),
  stickerBigDreamerClassic: require("@/assets/brand/stickers/sticker_big_dreamer.png"),
  stickerChallengeComplete: require("@/assets/brand/stickers/sticker_challenge_complete.png"),
  stickerProudOfYou: require("@/assets/brand/stickers/sticker_proud_of_you.png"),
  stickerAlmostThere: require("@/assets/brand/stickers/sticker_almost_there.png"),
  stickerOneStepCloser: require("@/assets/brand/stickers/sticker_one_step_closer.png"),
  stickerYouGotThisBubble: require("@/assets/brand/stickers/sticker_you_got_this_bubble.png"),
  stickerSmallStepsV3: require("@/assets/brand/stickers/sticker_small_steps_v3.png"),
  stickerFocusedClassic: require("@/assets/brand/stickers/sticker_focused.png"),
} as const;

export type BrandAssetName = keyof typeof assets;

export const BRAND_ASSET_GROUPS = {
  mascots: [
    "mascotCelebrate",
    "mascotReading",
    "mascotActive",
    "mascotFocused",
    "mascotTrophy",
    "mascotStreak",
    "mascotStudying",
    "mascotBedtime",
    "mascotCheerful",
    "mascotMorning",
    "mascotHeart",
    "mascotSupportive",
    "mascotCelebrating",
    "mascotPoints",
    "mascotCurious",
    "mascotQuestion",
    "mascotIdea",
    "mascotCheering",
    "mascotStar",
    "mascotPrediction",
  ],
  states: [
    "statePointsEarned",
    "stateNewBadgeUnlocked",
    "stateAiAnalyzing",
    "stateNoFriends",
    "stateAiPredictionReady",
    "stateNoRewards",
    "stateChallengeSuccess",
    "statePredicting",
    "stateNoChallenges",
    "stateStreakContinues",
    "stateNetworkError",
    "statePurchaseComplete",
    "stateChallengeFailed",
    "stateLevelUp",
    "stateNoPredictions",
  ],
  frames: [
    "frameMidnight",
    "frameChampion",
    "frameRainbow",
    "frameAi",
    "framePurpleAura",
    "frameLove",
    "frameMintNature",
    "frameStar",
    "frameFire",
    "frameMintFlame",
    "frameSunny",
    "frameGalaxy",
    "frameBlueFlame",
    "frameGoldenSun",
  ],
  icons: [
    "iconLifestyle",
    "iconRewardShop",
    "iconPointsClassic",
    "iconFitnessClassic",
    "categoryWakeUp",
    "iconTrophy",
    "iconSuccess",
    "categoryMindfulness",
    "iconAiInsightV2",
    "iconRewards",
    "iconShop",
    "iconStudyV2",
    "iconStudy",
    "iconPrediction",
    "iconConfidence",
    "iconLifestyleV2",
    "iconPointsV2",
    "statusLocked",
    "iconAiInsight",
    "iconTrophyClassic",
    "statusDown",
    "iconStreak",
    "iconRewardShopV2",
    "iconStreakClassic",
    "iconChallenge",
    "categoryHealth",
    "iconLeaderboard",
    "categorySocial",
    "iconFailedClassic",
    "iconFitness",
    "iconPoints",
    "iconLifestyleClassic",
    "iconTrophyV2",
    "iconFitnessV2",
    "iconStreakV2",
    "statusUp",
    "iconLevelUp",
    "categoryProductivity",
    "iconStudyClassic",
    "categorySleep",
    "iconAiInsightClassic",
    "iconSuccessClassic",
    "iconFailed",
  ],
  badges: [
    "badgeMiniFirstChallenge",
    "badge7DayStreak",
    "badgeChallengeChampion",
    "badgeMiniFitnessHero",
    "badgePredictionMaster",
    "badgeMiniSocialButterfly",
    "badgeThreeDayStreak",
    "badgeNightOwl",
    "badgeFocusMode",
    "badgeMiniConsistentYou",
    "badgeStreakStarter",
    "badgeAiSlayer",
    "badge30DayStreak",
    "badgeFirstChallengeV2",
    "badgeEarlyBird",
    "badgeFirstChallenge",
    "badgeHabitHero",
    "badgeKnowledgeBuilder",
    "badgeAiExplorer",
    "badgePositiveHabits",
    "badgeBigAchiever",
    "badge7DayStreakV2",
    "badgeComeback",
    "badge14DayStreak",
    "badgeSevenDayStreak",
    "badgeConsistency",
    "badgeFitnessHeroClassic",
    "badgeMiniBigAchiever",
    "badgeKnowledgeBuilderV2",
    "badgeRewardHunter",
    "badgePerfectWeek",
    "badgeFirstChallengeClassic",
    "badgeFitnessHero",
    "badgeMiniKnowledge",
    "badgeMiniPositiveMindset",
    "badgeKnowledgeBuilderClassic",
    "badgeSocialButterfly",
    "badgeMini7DayStreak",
    "badgePointsCollector",
    "badgeGoalGetter",
    "badgeFitnessHeroV2",
  ],
  decor: [
    "decoPlant",
    "decoHeart",
    "decoArrowCurved",
    "decoSunFace",
    "decoArrowBlue",
    "decoSquiggle",
    "decoStar",
    "decoLinesBlue",
    "decoPlantBuddy",
    "decoBurstLines",
    "decoSun",
    "decoStudyStar",
    "decoHeartV2",
    "decoRainbowStar",
    "decoSparkleBlue",
    "decoRobot",
    "decoStarV2",
    "decoCrown",
  ],
  rewards: [
    "rewardFocusBeats",
    "rewardBookLover",
    "rewardPlantBuddy",
    "rewardChillCap",
  ],
  stickers: [
    "stickerFocused",
    "stickerLifePredictionsMadeFun",
    "stickerBrighterDays",
    "stickerYourFutureSelfSaysThanks",
    "stickerTitleProgressNotPerfect",
    "stickerEveryPrediction",
    "stickerMakeItAHabit",
    "stickerYouGotThisMascot",
    "stickerTitleBigDreamer",
    "stickerYouCalledIt",
    "stickerPlayfulEditorial",
    "stickerYouGotThisClassic",
    "stickerSmallStepsV2",
    "stickerNicePrediction",
    "stickerTitleFocusedV2",
    "stickerTitleBigDreamerV2",
    "stickerLevelUp",
    "stickerBuildTheHabit",
    "stickerNewStreak",
    "sticker21DayStreak",
    "stickerTitleFocused",
    "stickerTitleKindHuman",
    "stickerBetterEveryDay",
    "stickerKeepGoing",
    "stickerBelieveYourData",
    "stickerPredictPlanPlayGrow",
    "stickerLetsGo",
    "stickerSmallSteps",
    "stickerYouGotThis",
    "stickerSameYouBrighterFuture",
    "stickerBrighterDaysOutline",
    "stickerBigDreamer",
    "stickerGreatJob",
    "sticker87ChanceHappier",
    "stickerSmallStepsBigResults",
    "stickerKeepTheMomentum",
    "stickerBigDreamerClassic",
    "stickerChallengeComplete",
    "stickerProudOfYou",
    "stickerAlmostThere",
    "stickerOneStepCloser",
    "stickerYouGotThisBubble",
    "stickerSmallStepsV3",
    "stickerFocusedClassic",
  ],
} as const satisfies Record<string, readonly BrandAssetName[]>;

export function BrandAsset({
  name,
  style,
  label,
}: {
  name: BrandAssetName;
  style: StyleProp<ImageStyle>;
  label?: string;
}) {
  return (
    <Image
      source={assets[name]}
      style={style}
      contentFit="contain"
      accessibilityLabel={label}
      accessible={!!label}
    />
  );
}
